### ISSUE TITLE
Cannot start mimic

### ISSUE THREAD

**Issue by hhuang** [lukeredpath/mimic#6]
Every time i try to start mimic, i get the following error:

Here's  how I'm starting it:

``` ruby
Mimic.mimic do
  post "/heffalumps" do
    heffalump = HeffalumpModel.new(params)
    if heffalump.save
      response = heffalump.to_json
      [200, {'Content-Type' => 'application/json', 'Content-Length' => response.bytesize}, response]
    else
      response = heffalump.to_json
      [422, {'Content-Type' => 'application/json', 'Content-Length' => response.bytesize}, response]
    end
  end
end
```

and here's the stack trace:

```
/Users/hubert/.rbenv/versions/ree-1.8.7-2011.03/lib/ruby/gems/1.8/gems/mimic-0.4.3/lib/mimic.rb:101:in `wait_for_service': Socket did not open within 5 seconds (SocketError)
    from /Users/hubert/.rbenv/versions/ree-1.8.7-2011.03/lib/ruby/gems/1.8/gems/mimic-0.4.3/lib/mimic.rb:54:in `serve'
    from /Users/hubert/.rbenv/versions/ree-1.8.7-2011.03/lib/ruby/gems/1.8/gems/mimic-0.4.3/lib/mimic.rb:22:in `mimic'
    from /Users/hubert/.rbenv/versions/ree-1.8.7-2011.03/lib/ruby/gems/1.8/gems/mimic-0.4.3/lib/mimic.rb:20:in `tap'
    from /Users/hubert/.rbenv/versions/ree-1.8.7-2011.03/lib/ruby/gems/1.8/gems/mimic-0.4.3/lib/mimic.rb:20:in `mimic'
    from ./spec/support/mimic.rb:80
    from /Users/hubert/projects/dm-restful-adapter/spec/spec_helper.rb:2:in `require'
    from /Users/hubert/projects/dm-restful-adapter/spec/spec_helper.rb:2
    from /Users/hubert/projects/dm-restful-adapter/spec/dm-restful-adapter_spec.rb:1:in `require'
    from /Users/hubert/projects/dm-restful-adapter/spec/dm-restful-adapter_spec.rb:1
    from /Users/hubert/.rbenv/versions/ree-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rspec-core-2.9.0/lib/rspec/core/configuration.rb:746:in `load'
    from /Users/hubert/.rbenv/versions/ree-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rspec-core-2.9.0/lib/rspec/core/configuration.rb:746:in `load_spec_files'
    from /Users/hubert/.rbenv/versions/ree-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rspec-core-2.9.0/lib/rspec/core/configuration.rb:746:in `map'
    from /Users/hubert/.rbenv/versions/ree-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rspec-core-2.9.0/lib/rspec/core/configuration.rb:746:in `load_spec_files'
    from /Users/hubert/.rbenv/versions/ree-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rspec-core-2.9.0/lib/rspec/core/command_line.rb:22:in `run'
    from /Users/hubert/.rbenv/versions/ree-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rspec-core-2.9.0/lib/rspec/core/runner.rb:69:in `run'
    from /Users/hubert/.rbenv/versions/ree-1.8.7-2011.03/lib/ruby/gems/1.8/gems/rspec-core-2.9.0/lib/rspec/core/runner.rb:10:in `autorun'
    from /Users/hubert/.rbenv/versions/ree-1.8.7-2011.03/lib/ruby/gems/1.8/bin/rspec:19
```

**Comment by hhuang** [comment]
this is fixed if thin is part of the bundle. perhaps that needs to be a dependency of the latest.
